name: Update Sponsors

on:
  schedule:
    - cron: '0 0 1,15 * *' # Runs on the 1st and 15th of every month
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sponsors:
    name: Update Sponsors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          file: 'README.md'
          marker: 'sponsors'
          template: '<a href="https://github.com/{{{ login }}}"><img src="https://github.com/{{{ login }}}.png" width="60px" alt="{{{ login }}}" style="border-radius: 50%;" /></a>&nbsp;&nbsp;'
          active-only: false
          include-private: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "docs: update sponsors"
          title: "docs: update sponsors"
          body: "Update sponsors list in README.md"
          branch: "sponsors-update"
          base: "main"
          delete-branch: true
